### ISSUE TITLE
Add more explanation

### ISSUE THREAD

**Issue by zzo38** [MrSametBurgazoglu/GezginWebEngine#29]
Will you add some more explanations, please? I had been trying to look which new web browser engines written in C (and not based on Mozilla or Chromium or any of the other ones) will be good, and I have some ideas how to make a better one (including: allow end user to override everything, assume that you know what you are doing better than the document author does, make possibility of extensions written in C and loaded as dynamic or static libraries, and I have some other ideas too).

**Comment by MrSametBurgazoglu** [comment]
I also have ideas to make it better(not implemented yet). I currently working on css scraping(read css files and links to tell web engine what and how to draw). So for now this project is not like a web engine its more like read some stuff and set some properties, but it will be a web engine one day I hope. For now it can read html file, create html tree, set elements and css properties(not all of them).
I will thinking to create documents to how this web engine works. But before that I must finish css scraping. I think this will take a month.
